#!/usr/bin/env python3
"""Count signal toggles in a VCD as a proxy for dynamic power.

Dynamic power ~ alpha * C * V^2 * f. With V and f fixed, comparing RTL variants
comes down to switching activity (alpha) on each net. This counts per-bit 0<->1
transitions for every signal under a scope (default: the DUT instance).

Transitions to/from x/z and the initial value are not counted. Nets that are
aliases of each other (same VCD id) are counted once in the totals.

With --sta-activity FILE it also writes OpenSTA `set_power_activity` commands
(activity = toggles per clock cycle, duty = fraction of time high) for the
data inputs, so a power report starts from measured activity instead of a
guess. OpenSTA propagates activity from there through the logic and flops.

Usage:
    vcd_toggles.py <file.vcd> [--scope dut] [--clock clk] [--inputs areset_n,in]
                   [--summary-only] [--sta-activity out.tcl]
"""
import argparse
import sys


def parse_vcd(path, scope_name):
    """Return per-id names, widths, per-bit toggles and per-bit time-high.

    Bit lists are LSB first (index i is bit [i]).
    """
    names = {}       # id -> list of signal names inside the scope
    widths = {}
    toggles = {}     # id -> [toggles per bit]
    high = {}        # id -> [time spent at 1 per bit]
    last = {}        # id -> last known value string (MSB first, padded)
    since = {}       # id -> time of last value change
    scope = []
    in_scope_depth = None
    now = 0

    def account(ident, upto):
        prev = last[ident]
        for i, bit in enumerate(reversed(prev)):
            if bit == "1":
                high[ident][i] += upto - since[ident]
        since[ident] = upto

    with open(path) as f:
        for line in f:
            tok = line.split()
            if not tok:
                continue
            head = tok[0]

            if head == "$scope":
                scope.append(tok[2])
                if in_scope_depth is None and tok[2] == scope_name:
                    in_scope_depth = len(scope)
                continue
            if head == "$upscope":
                if in_scope_depth is not None and len(scope) == in_scope_depth:
                    in_scope_depth = None
                scope.pop()
                continue
            if head == "$var":
                if in_scope_depth is not None:
                    width, ident, name = int(tok[2]), tok[3], tok[4]
                    names.setdefault(ident, []).append(name)
                    widths[ident] = width
                    toggles.setdefault(ident, [0] * width)
                    high.setdefault(ident, [0] * width)
                continue
            if head.startswith("#"):
                now = int(head[1:])
                continue
            if head.startswith("$"):
                continue

            # Value change: scalar "0!" or vector "b0101 !"
            if head[0] in "bB":
                value, ident = head[1:], tok[1]
            elif head[0] in "01xzXZ":
                value, ident = head[0], head[1:]
            else:
                continue  # real values etc.
            if ident not in names:
                continue

            w = widths[ident]
            # VCD left-extends with 0 (or x/z if the MSB given is x/z)
            pad = value[0] if value[0] in "xzXZ" else "0"
            value = value.rjust(w, pad)[-w:]
            prev = last.get(ident)
            if prev is not None:
                account(ident, now)
                for i, (a, b) in enumerate(zip(reversed(prev), reversed(value))):
                    if a != b and a in "01" and b in "01":
                        toggles[ident][i] += 1
            else:
                since[ident] = now
            last[ident] = value

    for ident in last:
        account(ident, now)
    return names, widths, toggles, high, now


def write_sta_activity(path, names, toggles, high, end_time, cycles, input_ids):
    """Write OpenSTA set_power_activity commands for the (scalar) inputs."""
    with open(path, "w") as f:
        f.write("# Measured switching activity (generated by vcd_toggles.py)\n")
        f.write(f"# {cycles} clock cycles; activity = toggles per cycle\n")
        for ident in sorted(input_ids, key=lambda i: names[i][0]):
            act = toggles[ident][0] / cycles
            duty = high[ident][0] / end_time
            f.write(f"set_power_activity -input_ports [get_ports {names[ident][0]}]"
                    f" -activity {act:.4f} -duty {duty:.4f}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("vcd")
    ap.add_argument("--scope", default="dut", help="instance whose signals are counted")
    ap.add_argument("--clock", default="clk", help="clock signal (reported separately)")
    ap.add_argument("--inputs", default="areset_n,in",
                    help="comma-separated inputs, excluded from the internal total")
    ap.add_argument("--summary-only", action="store_true")
    ap.add_argument("--sta-activity", metavar="FILE",
                    help="write OpenSTA set_power_activity commands to FILE")
    args = ap.parse_args()

    names, widths, bit_toggles, high, end_time = parse_vcd(args.vcd, args.scope)
    if not names:
        sys.exit(f"no signals found under scope '{args.scope}' in {args.vcd}")
    toggles = {i: sum(t) for i, t in bit_toggles.items()}

    inputs = set(filter(None, args.inputs.split(",")))
    clock_ids = {i for i, n in names.items() if args.clock in n}
    input_ids = {i for i, n in names.items() if inputs & set(n)} - clock_ids
    internal_ids = set(names) - clock_ids - input_ids

    if not args.summary_only:
        print(f"{'signal':32s} {'bits':>4s} {'toggles':>8s}")
        for ident in sorted(names, key=lambda i: (-toggles[i], names[i][0])):
            label = " = ".join(names[ident])
            print(f"{label:32.32s} {widths[ident]:4d} {toggles[ident]:8d}")
        print()

    clock_edges = sum(toggles[i] for i in clock_ids)
    cycles = clock_edges // 2
    print(f"clock toggles      : {clock_edges}  ({cycles} cycles)")
    print(f"input toggles      : {sum(toggles[i] for i in input_ids)}")
    print(f"internal nets      : {sum(widths[i] for i in internal_ids)} bits")
    print(f"internal toggles   : {sum(toggles[i] for i in internal_ids)}")

    if args.sta_activity:
        if cycles == 0:
            sys.exit("no clock toggles found; cannot compute per-cycle activity")
        write_sta_activity(args.sta_activity, names, bit_toggles, high,
                           end_time, cycles, input_ids)


if __name__ == "__main__":
    main()
