/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "prepend_packet.sv:37.1-149.10" *)
module prepend_packet_header(clk_i, rst_i, start_of_packet_i, end_of_packet_i, data_i, byte_count_i, start_of_packet_o, end_of_packet_o, data_o, byte_count_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  (* force_downto = 32'd1 *)
  (* src = "prepend_packet.sv:111.17-111.32|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _366_;
  (* force_downto = 32'd1 *)
  (* src = "prepend_packet.sv:121.35-121.54|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _367_;
  (* force_downto = 32'd1 *)
  (* src = "prepend_packet.sv:140.32-140.59|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "1" *)
  wire [3:0] _368_;
  (* force_downto = 32'd1 *)
  (* src = "prepend_packet.sv:140.32-140.59|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _369_;
  (* force_downto = 32'd1 *)
  (* src = "prepend_packet.sv:140.32-140.59|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _370_;
  (* src = "prepend_packet.sv:48.25-48.37" *)
  input [2:0] byte_count_i;
  wire [2:0] byte_count_i;
  (* src = "prepend_packet.sv:53.25-53.37" *)
  output [2:0] byte_count_o;
  wire [2:0] byte_count_o;
  (* src = "prepend_packet.sv:58.16-58.30" *)
  reg [2:0] byte_count_o_r = 3'h0;
  (* src = "prepend_packet.sv:61.16-61.23" *)
  reg [31:0] carry_r = 32'd0;
  (* src = "prepend_packet.sv:42.24-42.29" *)
  input clk_i;
  wire clk_i;
  (* src = "prepend_packet.sv:47.25-47.31" *)
  input [63:0] data_i;
  wire [63:0] data_i;
  (* src = "prepend_packet.sv:60.16-60.26" *)
  reg [63:0] data_i_reg = 64'h0000000000000000;
  (* src = "prepend_packet.sv:52.25-52.31" *)
  output [63:0] data_o;
  wire [63:0] data_o;
  (* src = "prepend_packet.sv:57.16-57.24" *)
  reg [63:0] data_o_r = 64'h0000000000000000;
  (* src = "prepend_packet.sv:66.16-66.23" *)
  reg [3:0] end_c_r = 4'h0;
  (* src = "prepend_packet.sv:56.34-56.41" *)
  reg end_o_r = 1'h0;
  (* src = "prepend_packet.sv:46.25-46.40" *)
  input end_of_packet_i;
  wire end_of_packet_i;
  (* src = "prepend_packet.sv:51.25-51.40" *)
  output end_of_packet_o;
  wire end_of_packet_o;
  (* src = "prepend_packet.sv:65.16-65.29" *)
  reg [2:0] flush_count_r = 3'h0;
  (* src = "prepend_packet.sv:67.16-67.29" *)
  reg packet_active = 1'h0;
  (* src = "prepend_packet.sv:63.16-63.27" *)
  reg pending_end = 1'h0;
  (* src = "prepend_packet.sv:64.16-64.29" *)
  reg pending_flush = 1'h0;
  (* src = "prepend_packet.sv:43.24-43.29" *)
  input rst_i;
  wire rst_i;
  (* src = "prepend_packet.sv:56.16-56.25" *)
  reg start_o_r = 1'h0;
  (* src = "prepend_packet.sv:45.25-45.42" *)
  input start_of_packet_i;
  wire start_of_packet_i;
  (* src = "prepend_packet.sv:50.25-50.42" *)
  output start_of_packet_o;
  wire start_of_packet_o;
  assign _369_[0] = ~byte_count_i[0];
  assign _021_ = start_of_packet_i | pending_end;
  assign _022_ = packet_active | pending_flush;
  assign _023_ = _022_ | _021_;
  assign _024_ = pending_end & ~(start_of_packet_i);
  assign _025_ = _024_ & ~(pending_flush);
  assign _026_ = _023_ & ~(_025_);
  assign _027_ = pending_flush & ~(start_of_packet_i);
  assign _000_ = _026_ & ~(_027_);
  assign _001_ = _023_ & ~(_027_);
  assign _028_ = ~pending_flush;
  assign _029_ = ~(packet_active | pending_end);
  assign _002_ = _028_ & ~(_029_);
  assign _030_ = ~(rst_i | start_of_packet_i);
  assign _031_ = pending_flush | ~(pending_end);
  assign _007_ = _031_ | ~(_030_);
  assign _366_[0] = ~end_c_r[0];
  assign _032_ = end_c_r[2] & ~(end_c_r[3]);
  assign _033_ = end_c_r[1] | end_c_r[0];
  assign _034_ = _033_ | ~(_032_);
  assign _035_ = ~(end_c_r[3] | end_c_r[2]);
  assign _008_ = _034_ & ~(_035_);
  assign _036_ = start_of_packet_i | ~(_008_);
  assign _037_ = ~(_036_ | _031_);
  assign _003_ = _037_ & ~(rst_i);
  assign _038_ = ~(end_of_packet_i & packet_active);
  assign _039_ = pending_end | pending_flush;
  assign _040_ = _039_ | _038_;
  assign _004_ = _030_ & ~(_040_);
  assign _041_ = _021_ | pending_flush;
  assign _042_ = ~(_008_ & _028_);
  assign _043_ = _024_ & ~(_042_);
  assign _005_ = _041_ & ~(_043_);
  assign _006_ = ~(_030_ & _028_);
  assign _044_ = ~pending_end;
  assign _045_ = data_i_reg[34] & packet_active;
  assign _046_ = ~(end_c_r[1] & end_c_r[0]);
  assign _047_ = _046_ | ~(_035_);
  assign _048_ = end_c_r[0] | ~(end_c_r[1]);
  assign _049_ = _048_ | ~(_035_);
  assign _050_ = _049_ & _047_;
  assign _051_ = end_c_r[1] | ~(end_c_r[0]);
  assign _052_ = _035_ & ~(_051_);
  assign _053_ = _052_ | ~(_050_);
  assign _054_ = data_i_reg[34] & ~(_053_);
  assign _055_ = _008_ ? data_i_reg[34] : _054_;
  assign _315_ = pending_end ? _055_ : _045_;
  assign _056_ = data_i_reg[35] & packet_active;
  assign _057_ = data_i_reg[35] & ~(_053_);
  assign _058_ = _008_ ? data_i_reg[35] : _057_;
  assign _318_ = pending_end ? _058_ : _056_;
  assign _059_ = data_i_reg[38] & packet_active;
  assign _060_ = data_i_reg[38] & ~(_053_);
  assign _061_ = _008_ ? data_i_reg[38] : _060_;
  assign _319_ = pending_end ? _061_ : _059_;
  assign _062_ = data_i_reg[39] & packet_active;
  assign _063_ = data_i_reg[39] & ~(_053_);
  assign _064_ = _008_ ? data_i_reg[39] : _063_;
  assign _320_ = pending_end ? _064_ : _062_;
  assign _065_ = data_i_reg[40] & packet_active;
  assign _066_ = _050_ & ~(_052_);
  assign _067_ = data_i_reg[40] & ~(_047_);
  assign _068_ = _066_ ? data_i_reg[40] : _067_;
  assign _069_ = _008_ ? data_i_reg[40] : _068_;
  assign _321_ = pending_end ? _069_ : _065_;
  assign _070_ = data_i_reg[42] & packet_active;
  assign _071_ = data_i_reg[42] & ~(_047_);
  assign _072_ = _066_ ? data_i_reg[42] : _071_;
  assign _073_ = _008_ ? data_i_reg[42] : _072_;
  assign _298_ = pending_end ? _073_ : _070_;
  assign _074_ = data_i_reg[43] & packet_active;
  assign _075_ = data_i_reg[43] & ~(_047_);
  assign _076_ = _066_ ? data_i_reg[43] : _075_;
  assign _077_ = _008_ ? data_i_reg[43] : _076_;
  assign _299_ = pending_end ? _077_ : _074_;
  assign _078_ = data_i_reg[44] & packet_active;
  assign _079_ = data_i_reg[44] & ~(_047_);
  assign _080_ = _066_ ? data_i_reg[44] : _079_;
  assign _081_ = _008_ ? data_i_reg[44] : _080_;
  assign _300_ = pending_end ? _081_ : _078_;
  assign _082_ = data_i_reg[46] & packet_active;
  assign _083_ = data_i_reg[46] & ~(_047_);
  assign _084_ = _066_ ? data_i_reg[46] : _083_;
  assign _085_ = _008_ ? data_i_reg[46] : _084_;
  assign _301_ = pending_end ? _085_ : _082_;
  assign _086_ = data_i_reg[47] & packet_active;
  assign _087_ = data_i_reg[47] & ~(_047_);
  assign _088_ = _066_ ? data_i_reg[47] : _087_;
  assign _089_ = _008_ ? data_i_reg[47] : _088_;
  assign _302_ = pending_end ? _089_ : _086_;
  assign _090_ = data_i_reg[49] & packet_active;
  assign _091_ = data_i_reg[49] & ~(_047_);
  assign _092_ = data_i_reg[49] & ~(_049_);
  assign _093_ = _092_ | _091_;
  assign _094_ = _066_ ? data_i_reg[49] : _093_;
  assign _095_ = _008_ ? data_i_reg[49] : _094_;
  assign _303_ = pending_end ? _095_ : _090_;
  assign _096_ = data_i_reg[50] & packet_active;
  assign _097_ = data_i_reg[50] & ~(_047_);
  assign _098_ = data_i_reg[50] & ~(_049_);
  assign _099_ = _098_ | _097_;
  assign _100_ = _066_ ? data_i_reg[50] : _099_;
  assign _101_ = _008_ ? data_i_reg[50] : _100_;
  assign _304_ = pending_end ? _101_ : _096_;
  assign _102_ = data_i_reg[51] & packet_active;
  assign _103_ = data_i_reg[51] & ~(_047_);
  assign _104_ = data_i_reg[51] & ~(_049_);
  assign _105_ = _104_ | _103_;
  assign _106_ = _066_ ? data_i_reg[51] : _105_;
  assign _107_ = _008_ ? data_i_reg[51] : _106_;
  assign _305_ = pending_end ? _107_ : _102_;
  assign _108_ = data_i_reg[53] & packet_active;
  assign _109_ = data_i_reg[53] & ~(_047_);
  assign _110_ = data_i_reg[53] & ~(_049_);
  assign _111_ = _110_ | _109_;
  assign _112_ = _066_ ? data_i_reg[53] : _111_;
  assign _113_ = _008_ ? data_i_reg[53] : _112_;
  assign _306_ = pending_end ? _113_ : _108_;
  assign _114_ = data_i_reg[54] & packet_active;
  assign _115_ = data_i_reg[54] & ~(_047_);
  assign _116_ = data_i_reg[54] & ~(_049_);
  assign _117_ = _116_ | _115_;
  assign _118_ = _066_ ? data_i_reg[54] : _117_;
  assign _119_ = _008_ ? data_i_reg[54] : _118_;
  assign _307_ = pending_end ? _119_ : _114_;
  assign _120_ = data_i_reg[55] & packet_active;
  assign _121_ = data_i_reg[55] & ~(_047_);
  assign _122_ = data_i_reg[55] & ~(_049_);
  assign _123_ = _122_ | _121_;
  assign _124_ = _066_ ? data_i_reg[55] : _123_;
  assign _125_ = _008_ ? data_i_reg[55] : _124_;
  assign _308_ = pending_end ? _125_ : _120_;
  assign _126_ = data_i_reg[56] & packet_active;
  assign _309_ = pending_end ? data_i_reg[56] : _126_;
  assign _127_ = data_i_reg[57] & packet_active;
  assign _310_ = pending_end ? data_i_reg[57] : _127_;
  assign _128_ = data_i_reg[58] & packet_active;
  assign _311_ = pending_end ? data_i_reg[58] : _128_;
  assign _129_ = data_i_reg[59] & packet_active;
  assign _312_ = pending_end ? data_i_reg[59] : _129_;
  assign _130_ = data_i_reg[60] & packet_active;
  assign _313_ = pending_end ? data_i_reg[60] : _130_;
  assign _131_ = data_i_reg[61] & packet_active;
  assign _314_ = pending_end ? data_i_reg[61] : _131_;
  assign _132_ = data_i_reg[62] & packet_active;
  assign _316_ = pending_end ? data_i_reg[62] : _132_;
  assign _133_ = data_i_reg[63] & packet_active;
  assign _317_ = pending_end ? data_i_reg[63] : _133_;
  assign _134_ = carry_r[1] & packet_active;
  assign _135_ = pending_end ? carry_r[1] : _134_;
  assign _322_ = pending_flush ? carry_r[1] : _135_;
  assign _136_ = carry_r[5] & packet_active;
  assign _137_ = pending_end ? carry_r[5] : _136_;
  assign _323_ = pending_flush ? carry_r[5] : _137_;
  assign _138_ = carry_r[8] & packet_active;
  assign _139_ = pending_end ? carry_r[8] : _138_;
  assign _324_ = pending_flush ? carry_r[8] : _139_;
  assign _140_ = carry_r[9] & packet_active;
  assign _141_ = pending_end ? carry_r[9] : _140_;
  assign _325_ = pending_flush ? carry_r[9] : _141_;
  assign _142_ = carry_r[12] & packet_active;
  assign _143_ = pending_end ? carry_r[12] : _142_;
  assign _326_ = pending_flush ? carry_r[12] : _143_;
  assign _144_ = carry_r[13] & packet_active;
  assign _145_ = pending_end ? carry_r[13] : _144_;
  assign _327_ = pending_flush ? carry_r[13] : _145_;
  assign _146_ = carry_r[18] & packet_active;
  assign _147_ = pending_end ? carry_r[18] : _146_;
  assign _328_ = pending_flush ? carry_r[18] : _147_;
  assign _148_ = carry_r[22] & packet_active;
  assign _149_ = pending_end ? carry_r[22] : _148_;
  assign _329_ = pending_flush ? carry_r[22] : _149_;
  assign _150_ = carry_r[24] & packet_active;
  assign _151_ = pending_end ? carry_r[24] : _150_;
  assign _330_ = pending_flush ? carry_r[24] : _151_;
  assign _152_ = carry_r[26] & packet_active;
  assign _153_ = pending_end ? carry_r[26] : _152_;
  assign _331_ = pending_flush ? carry_r[26] : _153_;
  assign _154_ = carry_r[28] & packet_active;
  assign _155_ = pending_end ? carry_r[28] : _154_;
  assign _332_ = pending_flush ? carry_r[28] : _155_;
  assign _156_ = carry_r[30] & packet_active;
  assign _157_ = pending_end ? carry_r[30] : _156_;
  assign _333_ = pending_flush ? carry_r[30] : _157_;
  assign _158_ = ~(data_i_reg[32] & packet_active);
  assign _159_ = ~data_i_reg[32];
  assign _160_ = _053_ | _159_;
  assign _161_ = _008_ ? _159_ : _160_;
  assign _162_ = pending_end ? _161_ : _158_;
  assign _163_ = _028_ & ~(_162_);
  assign _334_ = _163_ | start_of_packet_i;
  assign _164_ = ~(data_i_reg[33] & packet_active);
  assign _165_ = ~data_i_reg[33];
  assign _166_ = _053_ | _165_;
  assign _167_ = _008_ ? _165_ : _166_;
  assign _168_ = pending_end ? _167_ : _164_;
  assign _169_ = _028_ & ~(_168_);
  assign _337_ = _169_ | start_of_packet_i;
  assign _170_ = ~(data_i_reg[36] & packet_active);
  assign _171_ = ~data_i_reg[36];
  assign _172_ = _053_ | _171_;
  assign _173_ = _008_ ? _171_ : _172_;
  assign _174_ = pending_end ? _173_ : _170_;
  assign _175_ = _028_ & ~(_174_);
  assign _351_ = _175_ | start_of_packet_i;
  assign _176_ = ~(data_i_reg[37] & packet_active);
  assign _177_ = ~data_i_reg[37];
  assign _178_ = _053_ | _177_;
  assign _179_ = _008_ ? _177_ : _178_;
  assign _180_ = pending_end ? _179_ : _176_;
  assign _181_ = _028_ & ~(_180_);
  assign _358_ = _181_ | start_of_packet_i;
  assign _182_ = ~(data_i_reg[41] & packet_active);
  assign _183_ = ~data_i_reg[41];
  assign _184_ = _047_ | _183_;
  assign _185_ = _066_ ? _183_ : _184_;
  assign _186_ = _008_ ? _183_ : _185_;
  assign _187_ = pending_end ? _186_ : _182_;
  assign _188_ = _028_ & ~(_187_);
  assign _361_ = _188_ | start_of_packet_i;
  assign _189_ = ~(data_i_reg[45] & packet_active);
  assign _190_ = ~data_i_reg[45];
  assign _191_ = _047_ | _190_;
  assign _192_ = _066_ ? _190_ : _191_;
  assign _193_ = _008_ ? _190_ : _192_;
  assign _194_ = pending_end ? _193_ : _189_;
  assign _195_ = _028_ & ~(_194_);
  assign _335_ = _195_ | start_of_packet_i;
  assign _196_ = ~(data_i_reg[48] & packet_active);
  assign _197_ = ~data_i_reg[48];
  assign _198_ = _047_ | _197_;
  assign _199_ = data_i_reg[48] & ~(_049_);
  assign _200_ = _198_ & ~(_199_);
  assign _201_ = _066_ ? _197_ : _200_;
  assign _202_ = _008_ ? _197_ : _201_;
  assign _203_ = pending_end ? _202_ : _196_;
  assign _204_ = _028_ & ~(_203_);
  assign _336_ = _204_ | start_of_packet_i;
  assign _205_ = ~(data_i_reg[52] & packet_active);
  assign _206_ = ~data_i_reg[52];
  assign _207_ = _047_ | _206_;
  assign _208_ = data_i_reg[52] & ~(_049_);
  assign _209_ = _207_ & ~(_208_);
  assign _210_ = _066_ ? _206_ : _209_;
  assign _211_ = _008_ ? _206_ : _210_;
  assign _212_ = pending_end ? _211_ : _205_;
  assign _213_ = _028_ & ~(_212_);
  assign _338_ = _213_ | start_of_packet_i;
  assign _214_ = carry_r[0] & packet_active;
  assign _215_ = pending_end ? carry_r[0] : _214_;
  assign _216_ = pending_flush ? carry_r[0] : _215_;
  assign _339_ = _216_ | start_of_packet_i;
  assign _217_ = carry_r[2] & packet_active;
  assign _218_ = pending_end ? carry_r[2] : _217_;
  assign _219_ = pending_flush ? carry_r[2] : _218_;
  assign _340_ = _219_ | start_of_packet_i;
  assign _220_ = carry_r[3] & packet_active;
  assign _221_ = pending_end ? carry_r[3] : _220_;
  assign _222_ = pending_flush ? carry_r[3] : _221_;
  assign _341_ = _222_ | start_of_packet_i;
  assign _223_ = carry_r[4] & packet_active;
  assign _224_ = pending_end ? carry_r[4] : _223_;
  assign _225_ = pending_flush ? carry_r[4] : _224_;
  assign _342_ = _225_ | start_of_packet_i;
  assign _226_ = carry_r[6] & packet_active;
  assign _227_ = pending_end ? carry_r[6] : _226_;
  assign _228_ = pending_flush ? carry_r[6] : _227_;
  assign _343_ = _228_ | start_of_packet_i;
  assign _229_ = carry_r[7] & packet_active;
  assign _230_ = pending_end ? carry_r[7] : _229_;
  assign _231_ = pending_flush ? carry_r[7] : _230_;
  assign _344_ = _231_ | start_of_packet_i;
  assign _232_ = carry_r[10] & packet_active;
  assign _233_ = pending_end ? carry_r[10] : _232_;
  assign _234_ = pending_flush ? carry_r[10] : _233_;
  assign _345_ = _234_ | start_of_packet_i;
  assign _235_ = carry_r[11] & packet_active;
  assign _236_ = pending_end ? carry_r[11] : _235_;
  assign _237_ = pending_flush ? carry_r[11] : _236_;
  assign _346_ = _237_ | start_of_packet_i;
  assign _238_ = carry_r[14] & packet_active;
  assign _239_ = pending_end ? carry_r[14] : _238_;
  assign _240_ = pending_flush ? carry_r[14] : _239_;
  assign _347_ = _240_ | start_of_packet_i;
  assign _241_ = carry_r[15] & packet_active;
  assign _242_ = pending_end ? carry_r[15] : _241_;
  assign _243_ = pending_flush ? carry_r[15] : _242_;
  assign _348_ = _243_ | start_of_packet_i;
  assign _244_ = carry_r[16] & packet_active;
  assign _245_ = pending_end ? carry_r[16] : _244_;
  assign _246_ = pending_flush ? carry_r[16] : _245_;
  assign _349_ = _246_ | start_of_packet_i;
  assign _247_ = carry_r[17] & packet_active;
  assign _248_ = pending_end ? carry_r[17] : _247_;
  assign _249_ = pending_flush ? carry_r[17] : _248_;
  assign _350_ = _249_ | start_of_packet_i;
  assign _250_ = carry_r[19] & packet_active;
  assign _251_ = pending_end ? carry_r[19] : _250_;
  assign _252_ = pending_flush ? carry_r[19] : _251_;
  assign _352_ = _252_ | start_of_packet_i;
  assign _253_ = carry_r[20] & packet_active;
  assign _254_ = pending_end ? carry_r[20] : _253_;
  assign _255_ = pending_flush ? carry_r[20] : _254_;
  assign _353_ = _255_ | start_of_packet_i;
  assign _256_ = carry_r[21] & packet_active;
  assign _257_ = pending_end ? carry_r[21] : _256_;
  assign _258_ = pending_flush ? carry_r[21] : _257_;
  assign _354_ = _258_ | start_of_packet_i;
  assign _259_ = carry_r[23] & packet_active;
  assign _260_ = pending_end ? carry_r[23] : _259_;
  assign _261_ = pending_flush ? carry_r[23] : _260_;
  assign _355_ = _261_ | start_of_packet_i;
  assign _262_ = carry_r[25] & packet_active;
  assign _263_ = pending_end ? carry_r[25] : _262_;
  assign _264_ = pending_flush ? carry_r[25] : _263_;
  assign _356_ = _264_ | start_of_packet_i;
  assign _265_ = carry_r[27] & packet_active;
  assign _266_ = pending_end ? carry_r[27] : _265_;
  assign _267_ = pending_flush ? carry_r[27] : _266_;
  assign _357_ = _267_ | start_of_packet_i;
  assign _268_ = carry_r[29] & packet_active;
  assign _269_ = pending_end ? carry_r[29] : _268_;
  assign _270_ = pending_flush ? carry_r[29] : _269_;
  assign _359_ = _270_ | start_of_packet_i;
  assign _271_ = carry_r[31] & packet_active;
  assign _272_ = pending_end ? carry_r[31] : _271_;
  assign _273_ = pending_flush ? carry_r[31] : _272_;
  assign _360_ = _273_ | start_of_packet_i;
  assign _274_ = _046_ & _033_;
  assign _367_[1] = ~_274_;
  assign _275_ = ~(end_c_r[1] | end_c_r[0]);
  assign _276_ = _275_ ^ end_c_r[2];
  assign _367_[2] = ~_276_;
  assign _277_ = _008_ | end_c_r[0];
  assign _278_ = pending_end & ~(_277_);
  assign _362_ = pending_flush ? flush_count_r[0] : _278_;
  assign _279_ = _274_ | _008_;
  assign _280_ = pending_end & ~(_279_);
  assign _363_ = pending_flush ? flush_count_r[1] : _280_;
  assign _281_ = _276_ | _008_;
  assign _282_ = pending_end & ~(_281_);
  assign _364_ = pending_flush ? flush_count_r[2] : _282_;
  assign _297_ = _044_ & ~(_038_);
  assign _283_ = data_i_reg[1] & ~(pending_flush);
  assign _013_ = _283_ | start_of_packet_i;
  assign _284_ = data_i_reg[3] & ~(pending_flush);
  assign _018_ = _284_ | start_of_packet_i;
  assign _285_ = data_i_reg[5] & ~(pending_flush);
  assign _019_ = _285_ | start_of_packet_i;
  assign _286_ = data_i_reg[9] & ~(pending_flush);
  assign _020_ = _286_ | start_of_packet_i;
  assign _287_ = data_i_reg[11] & ~(pending_flush);
  assign _009_ = _287_ | start_of_packet_i;
  assign _288_ = data_i_reg[13] & ~(pending_flush);
  assign _010_ = _288_ | start_of_packet_i;
  assign _289_ = data_i_reg[17] & ~(pending_flush);
  assign _011_ = _289_ | start_of_packet_i;
  assign _290_ = data_i_reg[19] & ~(pending_flush);
  assign _012_ = _290_ | start_of_packet_i;
  assign _291_ = data_i_reg[21] & ~(pending_flush);
  assign _014_ = _291_ | start_of_packet_i;
  assign _292_ = data_i_reg[25] & ~(pending_flush);
  assign _015_ = _292_ | start_of_packet_i;
  assign _293_ = data_i_reg[27] & ~(pending_flush);
  assign _016_ = _293_ | start_of_packet_i;
  assign _294_ = data_i_reg[29] & ~(pending_flush);
  assign _017_ = _294_ | start_of_packet_i;
  assign _370_[1] = byte_count_i[1] ^ byte_count_i[0];
  assign _295_ = byte_count_i[1] & byte_count_i[0];
  assign _370_[2] = _295_ ^ byte_count_i[2];
  assign _368_[2] = _295_ & byte_count_i[2];
  assign _296_ = pending_end & ~(_008_);
  assign _365_ = _296_ | pending_flush;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[0] <= 1'h0;
    else if (_002_) carry_r[0] <= data_i_reg[0];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[2] <= 1'h0;
    else if (_002_) carry_r[2] <= data_i_reg[2];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[4] <= 1'h0;
    else if (_002_) carry_r[4] <= data_i_reg[4];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[6] <= 1'h0;
    else if (_002_) carry_r[6] <= data_i_reg[6];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[7] <= 1'h0;
    else if (_002_) carry_r[7] <= data_i_reg[7];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[8] <= 1'h0;
    else if (_002_) carry_r[8] <= data_i_reg[8];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[10] <= 1'h0;
    else if (_002_) carry_r[10] <= data_i_reg[10];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[12] <= 1'h0;
    else if (_002_) carry_r[12] <= data_i_reg[12];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[14] <= 1'h0;
    else if (_002_) carry_r[14] <= data_i_reg[14];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[15] <= 1'h0;
    else if (_002_) carry_r[15] <= data_i_reg[15];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[16] <= 1'h0;
    else if (_002_) carry_r[16] <= data_i_reg[16];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[18] <= 1'h0;
    else if (_002_) carry_r[18] <= data_i_reg[18];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[20] <= 1'h0;
    else if (_002_) carry_r[20] <= data_i_reg[20];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[22] <= 1'h0;
    else if (_002_) carry_r[22] <= data_i_reg[22];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[23] <= 1'h0;
    else if (_002_) carry_r[23] <= data_i_reg[23];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[24] <= 1'h0;
    else if (_002_) carry_r[24] <= data_i_reg[24];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[26] <= 1'h0;
    else if (_002_) carry_r[26] <= data_i_reg[26];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[28] <= 1'h0;
    else if (_002_) carry_r[28] <= data_i_reg[28];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[30] <= 1'h0;
    else if (_002_) carry_r[30] <= data_i_reg[30];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) carry_r[31] <= 1'h0;
    else if (_002_) carry_r[31] <= data_i_reg[31];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) start_o_r <= 1'h0;
    else start_o_r <= start_of_packet_i;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[33] <= 1'h0;
    else data_o_r[33] <= _322_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[37] <= 1'h0;
    else data_o_r[37] <= _323_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[40] <= 1'h0;
    else data_o_r[40] <= _324_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[41] <= 1'h0;
    else data_o_r[41] <= _325_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[44] <= 1'h0;
    else data_o_r[44] <= _326_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[45] <= 1'h0;
    else data_o_r[45] <= _327_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[50] <= 1'h0;
    else data_o_r[50] <= _328_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[54] <= 1'h0;
    else data_o_r[54] <= _329_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[56] <= 1'h0;
    else data_o_r[56] <= _330_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[58] <= 1'h0;
    else data_o_r[58] <= _331_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[60] <= 1'h0;
    else data_o_r[60] <= _332_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) data_o_r[62] <= 1'h0;
    else data_o_r[62] <= _333_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[0] <= 1'h0;
    else data_o_r[0] <= _334_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[1] <= 1'h0;
    else data_o_r[1] <= _337_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[4] <= 1'h0;
    else data_o_r[4] <= _351_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[5] <= 1'h0;
    else data_o_r[5] <= _358_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[9] <= 1'h0;
    else data_o_r[9] <= _361_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[13] <= 1'h0;
    else data_o_r[13] <= _335_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[16] <= 1'h0;
    else data_o_r[16] <= _336_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[20] <= 1'h0;
    else data_o_r[20] <= _338_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[32] <= 1'h0;
    else data_o_r[32] <= _339_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[34] <= 1'h0;
    else data_o_r[34] <= _340_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[35] <= 1'h0;
    else data_o_r[35] <= _341_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[36] <= 1'h0;
    else data_o_r[36] <= _342_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[38] <= 1'h0;
    else data_o_r[38] <= _343_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[39] <= 1'h0;
    else data_o_r[39] <= _344_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[42] <= 1'h0;
    else data_o_r[42] <= _345_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[43] <= 1'h0;
    else data_o_r[43] <= _346_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[46] <= 1'h0;
    else data_o_r[46] <= _347_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[47] <= 1'h0;
    else data_o_r[47] <= _348_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[48] <= 1'h0;
    else data_o_r[48] <= _349_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[49] <= 1'h0;
    else data_o_r[49] <= _350_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[51] <= 1'h0;
    else data_o_r[51] <= _352_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[52] <= 1'h0;
    else data_o_r[52] <= _353_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[53] <= 1'h0;
    else data_o_r[53] <= _354_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[55] <= 1'h0;
    else data_o_r[55] <= _355_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[57] <= 1'h0;
    else data_o_r[57] <= _356_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[59] <= 1'h0;
    else data_o_r[59] <= _357_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[61] <= 1'h0;
    else data_o_r[61] <= _359_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_o_r[63] <= 1'h0;
    else data_o_r[63] <= _360_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) end_o_r <= 1'h0;
    else end_o_r <= _365_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[2] <= 1'h0;
    else data_o_r[2] <= _315_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[3] <= 1'h0;
    else data_o_r[3] <= _318_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[6] <= 1'h0;
    else data_o_r[6] <= _319_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[7] <= 1'h0;
    else data_o_r[7] <= _320_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[8] <= 1'h0;
    else data_o_r[8] <= _321_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[10] <= 1'h0;
    else data_o_r[10] <= _298_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[11] <= 1'h0;
    else data_o_r[11] <= _299_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[12] <= 1'h0;
    else data_o_r[12] <= _300_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[14] <= 1'h0;
    else data_o_r[14] <= _301_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[15] <= 1'h0;
    else data_o_r[15] <= _302_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[17] <= 1'h0;
    else data_o_r[17] <= _303_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[18] <= 1'h0;
    else data_o_r[18] <= _304_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[19] <= 1'h0;
    else data_o_r[19] <= _305_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[21] <= 1'h0;
    else data_o_r[21] <= _306_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[22] <= 1'h0;
    else data_o_r[22] <= _307_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[23] <= 1'h0;
    else data_o_r[23] <= _308_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[24] <= 1'h0;
    else data_o_r[24] <= _309_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[25] <= 1'h0;
    else data_o_r[25] <= _310_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[26] <= 1'h0;
    else data_o_r[26] <= _311_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[27] <= 1'h0;
    else data_o_r[27] <= _312_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[28] <= 1'h0;
    else data_o_r[28] <= _313_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[29] <= 1'h0;
    else data_o_r[29] <= _314_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[30] <= 1'h0;
    else data_o_r[30] <= _316_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_006_) data_o_r[31] <= 1'h0;
    else data_o_r[31] <= _317_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) byte_count_o_r[0] <= 1'h0;
    else byte_count_o_r[0] <= _362_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) byte_count_o_r[1] <= 1'h0;
    else byte_count_o_r[1] <= _363_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) byte_count_o_r[2] <= 1'h0;
    else byte_count_o_r[2] <= _364_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_007_) pending_flush <= 1'h0;
    else pending_flush <= _008_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[0] <= 1'h0;
    else if (_000_) data_i_reg[0] <= data_i[0];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[1] <= 1'h0;
    else if (_000_) data_i_reg[1] <= data_i[1];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[2] <= 1'h0;
    else if (_000_) data_i_reg[2] <= data_i[2];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[3] <= 1'h0;
    else if (_000_) data_i_reg[3] <= data_i[3];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[4] <= 1'h0;
    else if (_000_) data_i_reg[4] <= data_i[4];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[5] <= 1'h0;
    else if (_000_) data_i_reg[5] <= data_i[5];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[6] <= 1'h0;
    else if (_000_) data_i_reg[6] <= data_i[6];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[7] <= 1'h0;
    else if (_000_) data_i_reg[7] <= data_i[7];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[8] <= 1'h0;
    else if (_000_) data_i_reg[8] <= data_i[8];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[9] <= 1'h0;
    else if (_000_) data_i_reg[9] <= data_i[9];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[10] <= 1'h0;
    else if (_000_) data_i_reg[10] <= data_i[10];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[11] <= 1'h0;
    else if (_000_) data_i_reg[11] <= data_i[11];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[12] <= 1'h0;
    else if (_000_) data_i_reg[12] <= data_i[12];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[13] <= 1'h0;
    else if (_000_) data_i_reg[13] <= data_i[13];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[14] <= 1'h0;
    else if (_000_) data_i_reg[14] <= data_i[14];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[15] <= 1'h0;
    else if (_000_) data_i_reg[15] <= data_i[15];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[16] <= 1'h0;
    else if (_000_) data_i_reg[16] <= data_i[16];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[17] <= 1'h0;
    else if (_000_) data_i_reg[17] <= data_i[17];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[18] <= 1'h0;
    else if (_000_) data_i_reg[18] <= data_i[18];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[19] <= 1'h0;
    else if (_000_) data_i_reg[19] <= data_i[19];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[20] <= 1'h0;
    else if (_000_) data_i_reg[20] <= data_i[20];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[21] <= 1'h0;
    else if (_000_) data_i_reg[21] <= data_i[21];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[22] <= 1'h0;
    else if (_000_) data_i_reg[22] <= data_i[22];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[23] <= 1'h0;
    else if (_000_) data_i_reg[23] <= data_i[23];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[24] <= 1'h0;
    else if (_000_) data_i_reg[24] <= data_i[24];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[25] <= 1'h0;
    else if (_000_) data_i_reg[25] <= data_i[25];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[26] <= 1'h0;
    else if (_000_) data_i_reg[26] <= data_i[26];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[27] <= 1'h0;
    else if (_000_) data_i_reg[27] <= data_i[27];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[28] <= 1'h0;
    else if (_000_) data_i_reg[28] <= data_i[28];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[29] <= 1'h0;
    else if (_000_) data_i_reg[29] <= data_i[29];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[30] <= 1'h0;
    else if (_000_) data_i_reg[30] <= data_i[30];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[31] <= 1'h0;
    else if (_000_) data_i_reg[31] <= data_i[31];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[32] <= 1'h0;
    else if (_000_) data_i_reg[32] <= data_i[32];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[33] <= 1'h0;
    else if (_000_) data_i_reg[33] <= data_i[33];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[34] <= 1'h0;
    else if (_000_) data_i_reg[34] <= data_i[34];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[35] <= 1'h0;
    else if (_000_) data_i_reg[35] <= data_i[35];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[36] <= 1'h0;
    else if (_000_) data_i_reg[36] <= data_i[36];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[37] <= 1'h0;
    else if (_000_) data_i_reg[37] <= data_i[37];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[38] <= 1'h0;
    else if (_000_) data_i_reg[38] <= data_i[38];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[39] <= 1'h0;
    else if (_000_) data_i_reg[39] <= data_i[39];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[40] <= 1'h0;
    else if (_000_) data_i_reg[40] <= data_i[40];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[41] <= 1'h0;
    else if (_000_) data_i_reg[41] <= data_i[41];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[42] <= 1'h0;
    else if (_000_) data_i_reg[42] <= data_i[42];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[43] <= 1'h0;
    else if (_000_) data_i_reg[43] <= data_i[43];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[44] <= 1'h0;
    else if (_000_) data_i_reg[44] <= data_i[44];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[45] <= 1'h0;
    else if (_000_) data_i_reg[45] <= data_i[45];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[46] <= 1'h0;
    else if (_000_) data_i_reg[46] <= data_i[46];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[47] <= 1'h0;
    else if (_000_) data_i_reg[47] <= data_i[47];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[48] <= 1'h0;
    else if (_000_) data_i_reg[48] <= data_i[48];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[49] <= 1'h0;
    else if (_000_) data_i_reg[49] <= data_i[49];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[50] <= 1'h0;
    else if (_000_) data_i_reg[50] <= data_i[50];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[51] <= 1'h0;
    else if (_000_) data_i_reg[51] <= data_i[51];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[52] <= 1'h0;
    else if (_000_) data_i_reg[52] <= data_i[52];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[53] <= 1'h0;
    else if (_000_) data_i_reg[53] <= data_i[53];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[54] <= 1'h0;
    else if (_000_) data_i_reg[54] <= data_i[54];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[55] <= 1'h0;
    else if (_000_) data_i_reg[55] <= data_i[55];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[56] <= 1'h0;
    else if (_000_) data_i_reg[56] <= data_i[56];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[57] <= 1'h0;
    else if (_000_) data_i_reg[57] <= data_i[57];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[58] <= 1'h0;
    else if (_000_) data_i_reg[58] <= data_i[58];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[59] <= 1'h0;
    else if (_000_) data_i_reg[59] <= data_i[59];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[60] <= 1'h0;
    else if (_000_) data_i_reg[60] <= data_i[60];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[61] <= 1'h0;
    else if (_000_) data_i_reg[61] <= data_i[61];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[62] <= 1'h0;
    else if (_000_) data_i_reg[62] <= data_i[62];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) data_i_reg[63] <= 1'h0;
    else if (_000_) data_i_reg[63] <= data_i[63];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[1] <= 1'h0;
    else if (_001_) carry_r[1] <= _013_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[3] <= 1'h0;
    else if (_001_) carry_r[3] <= _018_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[5] <= 1'h0;
    else if (_001_) carry_r[5] <= _019_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[9] <= 1'h0;
    else if (_001_) carry_r[9] <= _020_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[11] <= 1'h0;
    else if (_001_) carry_r[11] <= _009_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[13] <= 1'h0;
    else if (_001_) carry_r[13] <= _010_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[17] <= 1'h0;
    else if (_001_) carry_r[17] <= _011_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[19] <= 1'h0;
    else if (_001_) carry_r[19] <= _012_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[21] <= 1'h0;
    else if (_001_) carry_r[21] <= _014_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[25] <= 1'h0;
    else if (_001_) carry_r[25] <= _015_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[27] <= 1'h0;
    else if (_001_) carry_r[27] <= _016_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) carry_r[29] <= 1'h0;
    else if (_001_) carry_r[29] <= _017_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (!_030_) pending_end <= 1'h0;
    else if (!pending_flush) pending_end <= _297_;
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_003_) flush_count_r[0] <= _366_[0];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_003_) flush_count_r[1] <= _367_[1];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_003_) flush_count_r[2] <= _367_[2];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_004_) end_c_r[0] <= _369_[0];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_004_) end_c_r[1] <= _370_[1];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_004_) end_c_r[2] <= _370_[2];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (_004_) end_c_r[3] <= _368_[2];
  (* src = "prepend_packet.sv:74.5-147.8" *)
  always @(posedge clk_i)
    if (rst_i) packet_active <= 1'h0;
    else if (_005_) packet_active <= start_of_packet_i;
  assign _367_[0] = _366_[0];
  assign { _368_[3], _368_[0] } = { 1'h0, byte_count_i[0] };
  assign _369_[3:1] = { 1'h0, byte_count_i[2:1] };
  assign { _370_[3], _370_[0] } = { _368_[2], _369_[0] };
  assign byte_count_o = byte_count_o_r;
  assign data_o = data_o_r;
  assign end_of_packet_o = end_o_r;
  assign start_of_packet_o = start_o_r;
endmodule
